# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'theaMainInterface.ui'
#
# Created: Wed Jul 31 11:24:56 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1186, 764)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtGui.QFrame.StyledPanel)
        self.splitter.setFrameShadow(QtGui.QFrame.Plain)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.gridLayoutWidget = QtGui.QWidget(self.splitter)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.splitter_2 = QtGui.QSplitter(self.gridLayoutWidget)
        self.splitter_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.frame = QtGui.QFrame(self.splitter_2)
        self.frame.setMinimumSize(QtCore.QSize(300, 200))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtGui.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.matplotlibDisplay = matplotlibWidget(self.frame)
        self.matplotlibDisplay.setObjectName("matplotlibDisplay")
        self.gridLayout_6.addWidget(self.matplotlibDisplay, 1, 0, 1, 1)
        self.cubeInfoTab = QtGui.QTabWidget(self.splitter_2)
        self.cubeInfoTab.setMinimumSize(QtCore.QSize(300, 0))
        self.cubeInfoTab.setObjectName("cubeInfoTab")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtGui.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.printCubeBrowser = QtGui.QTextBrowser(self.tab_3)
        self.printCubeBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.printCubeBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.printCubeBrowser.setObjectName("printCubeBrowser")
        self.gridLayout.addWidget(self.printCubeBrowser, 0, 0, 1, 1)
        self.cubeInfoTab.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.printCubeSliceBrowser = QtGui.QTextBrowser(self.tab_4)
        self.printCubeSliceBrowser.setObjectName("printCubeSliceBrowser")
        self.gridLayout_2.addWidget(self.printCubeSliceBrowser, 0, 0, 1, 1)
        self.cubeInfoTab.addTab(self.tab_4, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.dataViewer = QtGui.QTableWidget(self.tab_2)
        self.dataViewer.setObjectName("dataViewer")
        self.dataViewer.setColumnCount(0)
        self.dataViewer.setRowCount(0)
        self.gridLayout_8.addWidget(self.dataViewer, 0, 0, 1, 1)
        self.cubeInfoTab.addTab(self.tab_2, "")
        self.gridLayout_3.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.splitter)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.gridLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectCube = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.selectCube.setMinimumSize(QtCore.QSize(100, 40))
        self.selectCube.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectCube.setObjectName("selectCube")
        self.verticalLayout.addWidget(self.selectCube)
        self.frame_2 = QtGui.QFrame(self.gridLayoutWidget_2)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_3.setObjectName("label_3")
        self.gridLayout_9.addWidget(self.label_3, 0, 0, 1, 2)
        self.selectDimension1 = QtGui.QComboBox(self.frame_2)
        self.selectDimension1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectDimension1.setObjectName("selectDimension1")
        self.gridLayout_9.addWidget(self.selectDimension1, 1, 0, 1, 2)
        self.selectDimension2 = QtGui.QComboBox(self.frame_2)
        self.selectDimension2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectDimension2.setObjectName("selectDimension2")
        self.gridLayout_9.addWidget(self.selectDimension2, 2, 0, 1, 2)
        self.line = QtGui.QFrame(self.frame_2)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_9.addWidget(self.line, 3, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 4, 0, 1, 2)
        self.selectSlicedDim = QtGui.QComboBox(self.frame_2)
        self.selectSlicedDim.setEnabled(False)
        self.selectSlicedDim.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectSlicedDim.setObjectName("selectSlicedDim")
        self.gridLayout_9.addWidget(self.selectSlicedDim, 5, 0, 1, 2)
        self.selectSliceCombo = QtGui.QComboBox(self.frame_2)
        self.selectSliceCombo.setEnabled(False)
        self.selectSliceCombo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectSliceCombo.setObjectName("selectSliceCombo")
        self.gridLayout_9.addWidget(self.selectSliceCombo, 7, 0, 1, 1)
        self.line_2 = QtGui.QFrame(self.frame_2)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_9.addWidget(self.line_2, 9, 0, 1, 2)
        self.label_5 = QtGui.QLabel(self.frame_2)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_5.setObjectName("label_5")
        self.gridLayout_9.addWidget(self.label_5, 10, 0, 1, 2)
        self.collapsedDim2 = QtGui.QLabel(self.frame_2)
        self.collapsedDim2.setText("")
        self.collapsedDim2.setObjectName("collapsedDim2")
        self.gridLayout_9.addWidget(self.collapsedDim2, 15, 0, 1, 1)
        self.selectSliceScroll = QtGui.QScrollBar(self.frame_2)
        self.selectSliceScroll.setEnabled(False)
        self.selectSliceScroll.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.selectSliceScroll.setOrientation(QtCore.Qt.Horizontal)
        self.selectSliceScroll.setObjectName("selectSliceScroll")
        self.gridLayout_9.addWidget(self.selectSliceScroll, 7, 1, 1, 1)
        self.selectSliceIndex2 = QtGui.QComboBox(self.frame_2)
        self.selectSliceIndex2.setEnabled(False)
        self.selectSliceIndex2.setFrame(True)
        self.selectSliceIndex2.setObjectName("selectSliceIndex2")
        self.gridLayout_9.addWidget(self.selectSliceIndex2, 15, 1, 1, 1)
        self.selectSliceIndex3 = QtGui.QComboBox(self.frame_2)
        self.selectSliceIndex3.setEnabled(False)
        self.selectSliceIndex3.setObjectName("selectSliceIndex3")
        self.gridLayout_9.addWidget(self.selectSliceIndex3, 18, 1, 1, 1)
        self.selectSliceIndex4 = QtGui.QComboBox(self.frame_2)
        self.selectSliceIndex4.setEnabled(False)
        self.selectSliceIndex4.setObjectName("selectSliceIndex4")
        self.gridLayout_9.addWidget(self.selectSliceIndex4, 17, 1, 1, 1)
        self.selectSliceIndex5 = QtGui.QComboBox(self.frame_2)
        self.selectSliceIndex5.setEnabled(False)
        self.selectSliceIndex5.setObjectName("selectSliceIndex5")
        self.gridLayout_9.addWidget(self.selectSliceIndex5, 19, 1, 1, 1)
        self.selectSliceIndex6 = QtGui.QComboBox(self.frame_2)
        self.selectSliceIndex6.setEnabled(False)
        self.selectSliceIndex6.setObjectName("selectSliceIndex6")
        self.gridLayout_9.addWidget(self.selectSliceIndex6, 20, 1, 1, 1)
        self.collapsedDim3 = QtGui.QLabel(self.frame_2)
        self.collapsedDim3.setText("")
        self.collapsedDim3.setObjectName("collapsedDim3")
        self.gridLayout_9.addWidget(self.collapsedDim3, 17, 0, 1, 1)
        self.collapsedDim4 = QtGui.QLabel(self.frame_2)
        self.collapsedDim4.setText("")
        self.collapsedDim4.setObjectName("collapsedDim4")
        self.gridLayout_9.addWidget(self.collapsedDim4, 18, 0, 1, 1)
        self.collapsedDim5 = QtGui.QLabel(self.frame_2)
        self.collapsedDim5.setText("")
        self.collapsedDim5.setObjectName("collapsedDim5")
        self.gridLayout_9.addWidget(self.collapsedDim5, 19, 0, 1, 1)
        self.collapsedDim6 = QtGui.QLabel(self.frame_2)
        self.collapsedDim6.setText("")
        self.collapsedDim6.setObjectName("collapsedDim6")
        self.gridLayout_9.addWidget(self.collapsedDim6, 20, 0, 1, 1)
        self.selectSliceIndex1 = QtGui.QComboBox(self.frame_2)
        self.selectSliceIndex1.setEnabled(False)
        self.selectSliceIndex1.setObjectName("selectSliceIndex1")
        self.gridLayout_9.addWidget(self.selectSliceIndex1, 13, 1, 1, 1)
        self.collapsedDim1 = QtGui.QLabel(self.frame_2)
        self.collapsedDim1.setText("")
        self.collapsedDim1.setObjectName("collapsedDim1")
        self.gridLayout_9.addWidget(self.collapsedDim1, 13, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.updateButton = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.updateButton.setMinimumSize(QtCore.QSize(0, 40))
        self.updateButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.updateButton.setObjectName("updateButton")
        self.verticalLayout.addWidget(self.updateButton)
        self.gridLayout_5.addWidget(self.splitter, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.dockWidget_2 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_2.setFeatures(QtGui.QDockWidget.DockWidgetMovable|QtGui.QDockWidget.DockWidgetVerticalTitleBar)
        self.dockWidget_2.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_7 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_6 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_7.addWidget(self.label_8, 0, 5, 1, 1)
        self.label_9 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 0, 7, 1, 1)
        self.selectPlotType = QtGui.QComboBox(self.dockWidgetContents_2)
        self.selectPlotType.setMinimumSize(QtCore.QSize(200, 0))
        self.selectPlotType.setObjectName("selectPlotType")
        self.selectPlotType.addItem("")
        self.selectPlotType.addItem("")
        self.selectPlotType.addItem("")
        self.gridLayout_7.addWidget(self.selectPlotType, 5, 1, 1, 1)
        self.selectProjection = QtGui.QComboBox(self.dockWidgetContents_2)
        self.selectProjection.setMinimumSize(QtCore.QSize(200, 0))
        self.selectProjection.setObjectName("selectProjection")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.selectProjection.addItem("")
        self.gridLayout_7.addWidget(self.selectProjection, 5, 3, 1, 1)
        self.selectColormap = QtGui.QComboBox(self.dockWidgetContents_2)
        self.selectColormap.setMinimumSize(QtCore.QSize(200, 0))
        self.selectColormap.setObjectName("selectColormap")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.selectColormap.addItem("")
        self.gridLayout_7.addWidget(self.selectColormap, 5, 5, 1, 1)
        self.contourSlider = QtGui.QSlider(self.dockWidgetContents_2)
        self.contourSlider.setMinimumSize(QtCore.QSize(50, 0))
        self.contourSlider.setMaximumSize(QtCore.QSize(200, 16777215))
        self.contourSlider.setMinimum(4)
        self.contourSlider.setMaximum(50)
        self.contourSlider.setProperty("value", 25)
        self.contourSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contourSlider.setObjectName("contourSlider")
        self.gridLayout_7.addWidget(self.contourSlider, 5, 7, 1, 2)
        self.contourLabel = QtGui.QLabel(self.dockWidgetContents_2)
        self.contourLabel.setObjectName("contourLabel")
        self.gridLayout_7.addWidget(self.contourLabel, 0, 8, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_2)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCoastlines = QtGui.QAction(MainWindow)
        self.actionCoastlines.setCheckable(True)
        self.actionCoastlines.setChecked(True)
        self.actionCoastlines.setObjectName("actionCoastlines")
        self.actionGridlines = QtGui.QAction(MainWindow)
        self.actionGridlines.setCheckable(True)
        self.actionGridlines.setChecked(True)
        self.actionGridlines.setObjectName("actionGridlines")
        self.actionCountry_Boundaries = QtGui.QAction(MainWindow)
        self.actionCountry_Boundaries.setCheckable(True)
        self.actionCountry_Boundaries.setObjectName("actionCountry_Boundaries")
        self.actionRivers_and_Lakes = QtGui.QAction(MainWindow)
        self.actionRivers_and_Lakes.setCheckable(True)
        self.actionRivers_and_Lakes.setObjectName("actionRivers_and_Lakes")
        self.actionNextSlice = QtGui.QAction(MainWindow)
        self.actionNextSlice.setEnabled(False)
        self.actionNextSlice.setVisible(True)
        self.actionNextSlice.setIconVisibleInMenu(False)
        self.actionNextSlice.setObjectName("actionNextSlice")
        self.actionPreviousSlice = QtGui.QAction(MainWindow)
        self.actionPreviousSlice.setEnabled(False)
        self.actionPreviousSlice.setVisible(True)
        self.actionPreviousSlice.setObjectName("actionPreviousSlice")
        self.actionFix_Colorbar = QtGui.QAction(MainWindow)
        self.actionFix_Colorbar.setCheckable(True)
        self.actionFix_Colorbar.setEnabled(False)
        self.actionFix_Colorbar.setVisible(False)
        self.actionFix_Colorbar.setObjectName("actionFix_Colorbar")
        self.actionColorbar = QtGui.QAction(MainWindow)
        self.actionColorbar.setObjectName("actionColorbar")
        self.actionPlot_Menu = QtGui.QAction(MainWindow)
        self.actionPlot_Menu.setCheckable(True)
        self.actionPlot_Menu.setChecked(True)
        self.actionPlot_Menu.setObjectName("actionPlot_Menu")
        self.actionContour_Labels = QtGui.QAction(MainWindow)
        self.actionContour_Labels.setCheckable(True)
        self.actionContour_Labels.setChecked(True)
        self.actionContour_Labels.setEnabled(False)
        self.actionContour_Labels.setVisible(True)
        self.actionContour_Labels.setObjectName("actionContour_Labels")
        self.actionFull_Screen = QtGui.QAction(MainWindow)
        self.actionFull_Screen.setCheckable(True)
        self.actionFull_Screen.setVisible(False)
        self.actionFull_Screen.setObjectName("actionFull_Screen")
        self.actionLoadSlices = QtGui.QAction(MainWindow)
        self.actionLoadSlices.setCheckable(True)
        self.actionLoadSlices.setEnabled(False)
        self.actionLoadSlices.setVisible(False)
        self.actionLoadSlices.setObjectName("actionLoadSlices")
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionPreviousSlice)
        self.toolBar.addAction(self.actionNextSlice)
        self.toolBar.addAction(self.actionCoastlines)
        self.toolBar.addAction(self.actionGridlines)
        self.toolBar.addAction(self.actionContour_Labels)
        self.toolBar.addAction(self.actionCountry_Boundaries)
        self.toolBar.addAction(self.actionRivers_and_Lakes)
        self.toolBar.addAction(self.actionFix_Colorbar)
        self.toolBar.addAction(self.actionColorbar)
        self.toolBar.addAction(self.actionLoadSlices)
        self.toolBar.addAction(self.actionPlot_Menu)
        self.toolBar.addAction(self.actionFull_Screen)
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.cubeInfoTab.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.contourSlider, QtCore.SIGNAL("valueChanged(int)"), self.contourLabel.setNum)
        QtCore.QObject.connect(self.selectSliceCombo, QtCore.SIGNAL("currentIndexChanged(int)"), self.selectSliceScroll.setValue)
        QtCore.QObject.connect(self.selectSliceScroll, QtCore.SIGNAL("valueChanged(int)"), self.selectSliceCombo.setCurrentIndex)
        QtCore.QObject.connect(self.actionPlot_Menu, QtCore.SIGNAL("toggled(bool)"), self.dockWidget_2.setVisible)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Thea Demo", None, QtGui.QApplication.UnicodeUTF8))
        self.cubeInfoTab.setTabText(self.cubeInfoTab.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "Full Cube", None, QtGui.QApplication.UnicodeUTF8))
        self.cubeInfoTab.setTabText(self.cubeInfoTab.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "Plotted Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.cubeInfoTab.setTabText(self.cubeInfoTab.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Slice Data", None, QtGui.QApplication.UnicodeUTF8))
        self.selectCube.setToolTip(QtGui.QApplication.translate("MainWindow", "Select which cube to view from the current file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Axes Dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.selectDimension1.setToolTip(QtGui.QApplication.translate("MainWindow", "Selects the Dimensions to be plotted against", None, QtGui.QApplication.UnicodeUTF8))
        self.selectDimension2.setToolTip(QtGui.QApplication.translate("MainWindow", "Selects the Dimensions to be plotted against", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Sliced Dimension", None, QtGui.QApplication.UnicodeUTF8))
        self.selectSlicedDim.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the dimension that you wish to take slices through", None, QtGui.QApplication.UnicodeUTF8))
        self.selectSliceCombo.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the slice you wish to view", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Collapsed Dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.selectSliceScroll.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the slice you wish to view", None, QtGui.QApplication.UnicodeUTF8))
        self.selectSliceIndex2.setToolTip(QtGui.QApplication.translate("MainWindow", "select the slice you wish to view", None, QtGui.QApplication.UnicodeUTF8))
        self.selectSliceIndex3.setToolTip(QtGui.QApplication.translate("MainWindow", "select the slice you wish to view", None, QtGui.QApplication.UnicodeUTF8))
        self.selectSliceIndex4.setToolTip(QtGui.QApplication.translate("MainWindow", "select the slice you wish to view", None, QtGui.QApplication.UnicodeUTF8))
        self.selectSliceIndex5.setToolTip(QtGui.QApplication.translate("MainWindow", "select the slice you wish to view", None, QtGui.QApplication.UnicodeUTF8))
        self.selectSliceIndex6.setToolTip(QtGui.QApplication.translate("MainWindow", "select the slice you wish to view", None, QtGui.QApplication.UnicodeUTF8))
        self.selectSliceIndex1.setToolTip(QtGui.QApplication.translate("MainWindow", "select the slice you wish to view", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setToolTip(QtGui.QApplication.translate("MainWindow", "Click this Button to apply changes to the plot", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setText(QtGui.QApplication.translate("MainWindow", "Update Image", None, QtGui.QApplication.UnicodeUTF8))
        self.updateButton.setShortcut(QtGui.QApplication.translate("MainWindow", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Plot Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Plot Projection", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Colour Scheme", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "No. of Contours  = ", None, QtGui.QApplication.UnicodeUTF8))
        self.selectPlotType.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the type of plot to be used", None, QtGui.QApplication.UnicodeUTF8))
        self.selectPlotType.setItemText(0, QtGui.QApplication.translate("MainWindow", "Filled Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.selectPlotType.setItemText(1, QtGui.QApplication.translate("MainWindow", "Contour", None, QtGui.QApplication.UnicodeUTF8))
        self.selectPlotType.setItemText(2, QtGui.QApplication.translate("MainWindow", "pcolormesh", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setToolTip(QtGui.QApplication.translate("MainWindow", "select the map projection to be used", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(0, QtGui.QApplication.translate("MainWindow", "Automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(1, QtGui.QApplication.translate("MainWindow", "Plate Carree", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(2, QtGui.QApplication.translate("MainWindow", "Lambert Cylindrical", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(3, QtGui.QApplication.translate("MainWindow", "Mercator", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(4, QtGui.QApplication.translate("MainWindow", "Miller", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(5, QtGui.QApplication.translate("MainWindow", "Mollweide", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(6, QtGui.QApplication.translate("MainWindow", "Orthographic", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(7, QtGui.QApplication.translate("MainWindow", "Robinson", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(8, QtGui.QApplication.translate("MainWindow", "Stereographic", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(9, QtGui.QApplication.translate("MainWindow", "Transverse Mercator", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(10, QtGui.QApplication.translate("MainWindow", "Interrupted Goode Homolosine", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(11, QtGui.QApplication.translate("MainWindow", "Rotated Pole", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(12, QtGui.QApplication.translate("MainWindow", "OSGB", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(13, QtGui.QApplication.translate("MainWindow", "EuroPP", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(14, QtGui.QApplication.translate("MainWindow", "Gnomonic", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(15, QtGui.QApplication.translate("MainWindow", "North Polar Stereo", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(16, QtGui.QApplication.translate("MainWindow", "OSNI", None, QtGui.QApplication.UnicodeUTF8))
        self.selectProjection.setItemText(17, QtGui.QApplication.translate("MainWindow", "South Polar Stereo", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setToolTip(QtGui.QApplication.translate("MainWindow", "Select the colour scheme to be used", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(0, QtGui.QApplication.translate("MainWindow", "Automatic", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(1, QtGui.QApplication.translate("MainWindow", "brewer_Accent_08", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(2, QtGui.QApplication.translate("MainWindow", "brewer_Blues_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(3, QtGui.QApplication.translate("MainWindow", "brewer_BrBG_11", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(4, QtGui.QApplication.translate("MainWindow", "brewer_BuGn_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(5, QtGui.QApplication.translate("MainWindow", "brewer_BuPu_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(6, QtGui.QApplication.translate("MainWindow", "brewer_Dark2_08", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(7, QtGui.QApplication.translate("MainWindow", "brewer_GnBu_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(8, QtGui.QApplication.translate("MainWindow", "brewer_Greens_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(9, QtGui.QApplication.translate("MainWindow", "brewer_Greys_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(10, QtGui.QApplication.translate("MainWindow", "brewer_OrRd_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(11, QtGui.QApplication.translate("MainWindow", "brewer_Oranges_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(12, QtGui.QApplication.translate("MainWindow", "brewer_PRGn_11", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(13, QtGui.QApplication.translate("MainWindow", "brewer_Paired_12", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(14, QtGui.QApplication.translate("MainWindow", "brewer_Pastel1_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(15, QtGui.QApplication.translate("MainWindow", "brewer_Pastel2_08", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(16, QtGui.QApplication.translate("MainWindow", "brewer_PiYG_11", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(17, QtGui.QApplication.translate("MainWindow", "brewer_PuBuGn_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(18, QtGui.QApplication.translate("MainWindow", "brewer_PuBu_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(19, QtGui.QApplication.translate("MainWindow", "brewer_PuOr_11", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(20, QtGui.QApplication.translate("MainWindow", "brewer_PuRd_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(21, QtGui.QApplication.translate("MainWindow", "brewer_Purples_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(22, QtGui.QApplication.translate("MainWindow", "brewer_RdBu_11", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(23, QtGui.QApplication.translate("MainWindow", "brewer_RdGy_11", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(24, QtGui.QApplication.translate("MainWindow", "brewer_RdPu_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(25, QtGui.QApplication.translate("MainWindow", "brewer_RdYlBu_11", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(26, QtGui.QApplication.translate("MainWindow", "brewer_RdYlGn_11", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(27, QtGui.QApplication.translate("MainWindow", "brewer_Reds_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(28, QtGui.QApplication.translate("MainWindow", "brewer_Set1_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(29, QtGui.QApplication.translate("MainWindow", "brewer_Set2_08", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(30, QtGui.QApplication.translate("MainWindow", "brewer_Set3_12", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(31, QtGui.QApplication.translate("MainWindow", "brewer_Spectral_11", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(32, QtGui.QApplication.translate("MainWindow", "brewer_YlGnBu_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(33, QtGui.QApplication.translate("MainWindow", "brewer_YlGn_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(34, QtGui.QApplication.translate("MainWindow", "brewer_YlOrBr_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(35, QtGui.QApplication.translate("MainWindow", "brewer_YlOrBr_09", None, QtGui.QApplication.UnicodeUTF8))
        self.selectColormap.setItemText(36, QtGui.QApplication.translate("MainWindow", "brewer_YlOrRd_09", None, QtGui.QApplication.UnicodeUTF8))
        self.contourSlider.setToolTip(QtGui.QApplication.translate("MainWindow", "select the number of contours to be plotted", None, QtGui.QApplication.UnicodeUTF8))
        self.contourLabel.setText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Esc", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCoastlines.setText(QtGui.QApplication.translate("MainWindow", "Coastlines", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCoastlines.setShortcut(QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGridlines.setText(QtGui.QApplication.translate("MainWindow", "Gridlines", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGridlines.setShortcut(QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCountry_Boundaries.setText(QtGui.QApplication.translate("MainWindow", "Country Boundaries", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCountry_Boundaries.setShortcut(QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRivers_and_Lakes.setText(QtGui.QApplication.translate("MainWindow", "Rivers and Lakes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRivers_and_Lakes.setShortcut(QtGui.QApplication.translate("MainWindow", "R", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNextSlice.setText(QtGui.QApplication.translate("MainWindow", "Next Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNextSlice.setShortcut(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreviousSlice.setText(QtGui.QApplication.translate("MainWindow", "Previous Slice", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPreviousSlice.setShortcut(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFix_Colorbar.setText(QtGui.QApplication.translate("MainWindow", "Fix Colorbar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFix_Colorbar.setShortcut(QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.actionColorbar.setText(QtGui.QApplication.translate("MainWindow", "Colorbar Range", None, QtGui.QApplication.UnicodeUTF8))
        self.actionColorbar.setShortcut(QtGui.QApplication.translate("MainWindow", "O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlot_Menu.setText(QtGui.QApplication.translate("MainWindow", "Plot Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPlot_Menu.setShortcut(QtGui.QApplication.translate("MainWindow", "M", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContour_Labels.setText(QtGui.QApplication.translate("MainWindow", "Contour Labels", None, QtGui.QApplication.UnicodeUTF8))
        self.actionContour_Labels.setShortcut(QtGui.QApplication.translate("MainWindow", "L", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFull_Screen.setText(QtGui.QApplication.translate("MainWindow", "Full Screen", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFull_Screen.setShortcut(QtGui.QApplication.translate("MainWindow", "Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadSlices.setText(QtGui.QApplication.translate("MainWindow", "Load All Slices", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadSlices.setToolTip(QtGui.QApplication.translate("MainWindow", "Loads all slices of the cube along the sliced dimension at once. This will then reduce the loading time between slices.", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoadSlices.setShortcut(QtGui.QApplication.translate("MainWindow", "L", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidgetFile import matplotlibWidget
